# Generated by Django 6.1.1 on 2026-09-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(blank=True, choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10, null=True),
        ),
    ]
