# Generated by Django 6.1.1 on 2026-09-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='direction',
        ),
    ]
