# Generated by Django 6.1.1 on 2026-09-14 20:37

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(db_index=True, default=transactions.models.generate_transaction_reference, max_length=50, unique=True),
        ),
    ]
